spring.application.name=eureka-server

# Server Port
server.port=8761

# Application Name
#spring.application.name=EUREKA-SERVER

# Eureka Configuration
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Hostname
eureka.instance.hostname=localhost

# Eureka Server
eureka.server.wait-time-in-ms-when-sync-empty=0

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
