spring.application.name=config-server

#server Port
server.port=8888

# Git Repository
spring.cloud.config.server.git.uri=https://gitlab.com/Ramachandrarao24/bank-application-microservices.git
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.skip-ssl-validation=true

# Eureka Registration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.enabled=false